### ISSUE TITLE
Changes that needs to be done!

### ISSUE THREAD

**Issue by JourneyOver** [JourneyOver/chocolatey-packages#1]
# Tasks

### Passthrough One
- [x] Redo/clean up all package coding 
- [x] Run through and fix up any mistakes and make readmes better as well

# Package Redo/Clean up
- [x] any2ico.portable
- [x] axcrypt
- [x] bsplayer
- [x] centbrowser
- [x] centbrowser beta
- [x] duckietv
- [x] duckietv prereleases
- [x] jackett
- [x] plasso
- [x] radarr
- [x] swift-im
- [x] tsedat
- [x] tvrenamer.portable
- [x] winpatrol

# Maybe
- [ ] ssip.portable
- [ ] ssip

# Run through and fix up any mistakes and make readmes better as well, make sure all pictures/icons point to master branch instead of dev branch.
- [x] any2ico.portable
- [x] axcrypt
- [x] bsplayer
- [x] centbrowser
- [x] centbrowser beta
- [x] duckietv
- [x] duckietv prereleases
- [x] jackett
- [x] plasso
- [x] radarr
- [x] swift-im
- [x] tsedat
- [x] tvrenamer.portable
- [x] winpatrol

# Maybe
- [ ] ssip.portable
- [ ] ssip

**Comment by JourneyOver** [comment]
# Tasks

### Passthrough Two
- [ ] Embed programs into packages where I can. [Embedded Package Info](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#114-embed-a-package-if-allowed)
- [ ] Retest Install/Uninstall of all packages

# Embed programs into packages where I can
- [x] any2ico.portable (Not Allowed)
- [ ] axcrypt
- [ ] basplayer
- [ ] centbrowser
- [ ] centbrowser beta
- [ ] duckietv
- [ ] duckietv prereleases
- [ ] jackett
- [ ] plasso
- [ ] radarr
- [ ] swift-im
- [ ] tsedat
- [ ] tvrenamer.portable
- [ ] winpatrol
- [ ] ssip.portable
- [ ] ssip

# Retest Install/Uninstall of all packages
- [ ] any2ico.portable
- [ ] axcrypt
- [ ] basplayer
- [ ] centbrowser
- [ ] centbrowser beta
- [ ] duckietv
- [ ] duckietv prereleases
- [ ] jackett
- [ ] plasso
- [ ] radarr
- [ ] swift-im
- [ ] tsedat
- [ ] tvrenamer.portable
- [ ] winpatrol
- [ ] ssip.portable
- [ ] ssip
